import type { MCTriviaQuestion } from './constants';

export const AVATAR_1_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: "What was the name of Jake Sully's twin brother, whom he was recruited to replace in the Avatar Program?",
    options: ['Thomas', 'Steven', 'Norman'],
    answer: 'Thomas',
    evidence: 'Source: avatar1.md, question 1',
  },
  {
    id: 2,
    question: 'According to the data provided by Parker Selfridge, what is the specific market value of Unobtanium?',
    options: ['$10 million per gram', '$20 million per kilogram', '$100 million per ton'],
    answer: '$20 million per kilogram',
    evidence: 'Source: avatar1.md, question 2',
  },
  {
    id: 3,
    question: 'True or False: The Na\'vi refer to the human-controlled hybrid bodies used by the RDA as "Dreamwalkers."',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar1.md, question 3',
  },
  {
    id: 4,
    question: 'What is the standard English translation for the profound Na\'vi greeting "Oel ngati kameie"?',
    options: ['I honor you', 'I see you', 'We are one'],
    answer: 'I see you',
    evidence: 'Source: avatar1.md, question 4',
  },
  {
    id: 5,
    question: 'How does a Mountain Banshee (Ikran) signify that it has successfully "chosen" a Na\'vi hunter to be its rider?',
    options: ['It bows its head in submission.', 'It presents a gift to the hunter.', 'It attempts to kill the hunter.'],
    answer: 'It attempts to kill the hunter.',
    evidence: 'Source: avatar1.md, question 5',
  },
  {
    id: 6,
    question: 'True or False: The Tsahìk is the clan\'s spiritual leader, specifically tasked with interpreting the will of Eywa.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar1.md, question 6',
  },
  {
    id: 7,
    question: 'What specific sequence of weaponry did Colonel Quaritch use to bring down the Omaticaya Hometree?',
    options: ['Sonic emitters followed by napalm', 'Gas canisters followed by incendiaries and rockets', 'Flashbangs followed by heavy artillery'],
    answer: 'Gas canisters followed by incendiaries and rockets',
    evidence: 'Source: avatar1.md, question 7',
  },
  {
    id: 8,
    question: 'True or False: Trudy Chacon demonstrated her defection by refusing to fire her rockets during the assault on Hometree.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar1.md, question 8',
  },
  {
    id: 9,
    question: 'During the Battle for the Tree of Souls, what method did Jake Sully use to neutralize the Valkyrie shuttle?',
    options: ['He used a longbow to hit the pilot through the glass.', 'He threw a grenade into the engine intake duct.', 'He sabotaged the fuel lines prior to the engagement.'],
    answer: 'He threw a grenade into the engine intake duct.',
    evidence: 'Source: avatar1.md, question 9',
  },
  {
    id: 10,
    question: "What is the final status of Jake Sully's consciousness at the conclusion of the film?",
    options: ['It is lost during the transfer ceremony.', 'It is permanently transferred into his Na\'vi avatar body.', 'It remains bound to the human body in a link bed.'],
    answer: 'It is permanently transferred into his Na\'vi avatar body.',
    evidence: 'Source: avatar1.md, question 10',
  },
];

export const AVATAR_2_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: 'Which of the following children in the Sully family are the biological offspring of Jake Sully and Neytiri?',
    options: ['Kiri, Spider, and Neteyam', 'Neteyam, Lo\'ak, and Tuktirey', 'Lo\'ak, Tuktirey, and Kiri', 'Neteyam, Lo\'ak, and Spider'],
    answer: 'Neteyam, Lo\'ak, and Tuktirey',
    evidence: 'Source: avatar2.md, question 1',
  },
  {
    id: 2,
    question: 'What physical genetic marker, inherited from Jake\'s human DNA, distinguishes the Sully children from a "normal" Na\'vi of the Metkayina clan?',
    options: ['They possess bioluminescent patterns on their chests.', 'They have four fingers and a thumb on each hand, instead of only three fingers.', 'They possess thinner tails designed for forest navigation rather than swimming.', 'They lack a neural queue (ponytail) for making a bond.'],
    answer: 'They have four fingers and a thumb on each hand, instead of only three fingers.',
    evidence: 'Source: avatar2.md, question 2',
  },
  {
    id: 3,
    question: 'Who is revealed to be the biological father of the human boy Miles "Spider" Quaritch?',
    options: ['Dr. Norm Spellman', 'Parker Selfridge', 'Colonel Miles Quaritch', 'Thomas Sully'],
    answer: 'Colonel Miles Quaritch',
    evidence: 'Source: avatar2.md, question 3',
  },
  {
    id: 4,
    question: 'What is the miraculous origin of the Sully family\'s adopted daughter, Kiri?',
    options: ['She is a clone created in an RDA laboratory.', 'She was born from Grace Augustine\'s avatar after the scientist had already died.', 'She was discovered inside a Spirit Tree pod after a Great Sorrow.', 'She is the biological daughter of Neytiri\'s sister, Silwanin.'],
    answer: 'She was born from Grace Augustine\'s avatar after the scientist had already died.',
    evidence: 'Source: avatar2.md, question 4',
  },
  {
    id: 5,
    question: 'Why is the Tulkun named Payakan considered an outcast by his pod and the Metkayina clan?',
    options: ['He was unable to form a neural bond with a Na\'vi rider.', 'He was wrongly accused of being violent.', 'He failed to protect the reef spirit tree during a storm.', 'He refused to share the precious brain oil with his kin.'],
    answer: 'He was wrongly accused of being violent.',
    evidence: 'Source: avatar2.md, question 5',
  },
  {
    id: 6,
    question: 'Which physical adaptation makes it most difficult for the Sully children to keep up with the native Metkayina during their training?',
    options: ['Their inability to form a neural bond with an Ilu.', 'Their reliance on Exopacks for deep-water dives.', 'Metkayina bodies are specifically built for swimming compared to the Omatikaya.', 'The lack of bioluminescent lures on their skin.'],
    answer: 'Metkayina bodies are specifically built for swimming compared to the Omatikaya.',
    evidence: 'Source: avatar2.md, question 6',
  },
  {
    id: 7,
    question: 'To which Na\'vi clan does Jake Sully take his family to seek refuge when the RDA returns to hunt him?',
    options: ['The Tipani', 'The Tayrangi', 'The Metkayina', 'The Omatikaya'],
    answer: 'The Metkayina',
    evidence: 'Source: avatar2.md, question 7',
  },
  {
    id: 8,
    question: 'The primary motivation for the humans\' return to Pandora after 16 years is the realization that Earth is dying and humanity requires a place for colonization.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar2.md, question 8',
  },
  {
    id: 9,
    question: 'The initial surprise attack against the human whaling vessel, which causes massive damage and chaos, was launched by the Tulkun named Payakan.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar2.md, question 9',
  },
  {
    id: 10,
    question: 'At the conclusion of the film, the primary antagonist, Colonel Quaritch, is rescued from drowning by his biological son, Spider.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar2.md, question 10',
  },
];

export const AVATAR_3_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: "Who is the leader of the Ash People introduced in 'Avatar: Fire and Ash'?",
    options: ['Mo\'at', 'Varang', 'Neytiri', 'Tsireya'],
    answer: 'Varang',
    evidence: 'Source: avatar3.md, question 1',
  },
  {
    id: 2,
    question: 'Which actor was cast in the pivotal role of Varang?',
    options: ['Zoe Saldana', 'Kate Winslet', 'Oona Chaplin', 'Bailey Bass'],
    answer: 'Oona Chaplin',
    evidence: 'Source: avatar3.md, question 2',
  },
  {
    id: 3,
    question: 'Which specific spirits appear at the end of the film to accept Spider as one of the people?',
    options: ['Grace and Neteyam', 'Eytukan and Tsu\'tey', 'Sylwanin and Eytukan', 'Tsu\'tey and Neteyam'],
    answer: 'Eytukan and Tsu\'tey',
    evidence: 'Source: avatar3.md, question 3',
  },
  {
    id: 4,
    question: "Sigourney Weaver performs 'Acting for Two' by appearing as both Kiri and the spirit of Grace Augustine in the same final scene.",
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar3.md, question 4',
  },
  {
    id: 5,
    question: 'What was the working title for the third Avatar film announced by James Cameron in 2018?',
    options: ['The Way of Water', 'The Tulkun Rider', 'The Seed Bearer', 'Fire and Ash'],
    answer: 'The Seed Bearer',
    evidence: 'Source: avatar3.md, question 5',
  },
  {
    id: 6,
    question: "The production of 'Avatar: Fire and Ash' was delayed nine times between its original 2015 window and its 2025 release.",
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar3.md, question 6',
  },
  {
    id: 7,
    question: "To which two late production members is 'Avatar: Fire and Ash' dedicated?",
    options: ['John Landau and James Cameron', 'John Refoua and Jon Landau', 'Sylvie Genty and John Refoua', 'Jon Landau and Stephen Lang'],
    answer: 'John Refoua and Jon Landau',
    evidence: 'Source: avatar3.md, question 7',
  },
  {
    id: 8,
    question: "In Hong Kong, the film's subtitle 'Fire and Ash' was retained despite a release delay to January 2026.",
    options: ['True', 'False'],
    answer: 'False',
    evidence: 'Source: avatar3.md, question 8',
  },
  {
    id: 9,
    question: "What is the wide theatrical release date for 'Avatar: Fire and Ash' in the United States?",
    options: ['December 14, 2022', 'December 17, 2025', 'December 19, 2025', 'January 8, 2026'],
    answer: 'December 19, 2025',
    evidence: 'Source: avatar3.md, question 9',
  },
  {
    id: 10,
    question: 'What was the professional role of Jon Landau within the Avatar franchise prior to his passing?',
    options: ['Director', 'Editor', 'Producer', 'Screenwriter'],
    answer: 'Producer',
    evidence: 'Source: avatar3.md, question 10',
  },
];

export const AVATAR_RANDOM_TRIVIA = [
  ...AVATAR_1_TRIVIA,
  ...AVATAR_2_TRIVIA,
  ...AVATAR_3_TRIVIA,
].map((question, index) => ({
  ...question,
  id: index + 1,
}));
