import type { MCTriviaQuestion } from './constants';

export const AVATAR_1_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: "What was the name of Jake Sully's twin brother, whom he was recruited to replace in the Avatar Program?",
    options: ['Thomas', 'Steven', 'Norman'],
    answer: 'Thomas',
    evidence: 'Source: avatar1.md, question 1',
  },
  {
    id: 2,
    question: 'According to the data provided by Parker Selfridge, what is the specific market value of Unobtanium?',
    options: ['$10 million per gram', '$20 million per kilogram', '$100 million per ton'],
    answer: '$20 million per kilogram',
    evidence: 'Source: avatar1.md, question 2',
  },
  {
    id: 3,
    question: 'True or False: The Na\'vi refer to the human-controlled hybrid bodies used by the RDA as "Dreamwalkers."',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar1.md, question 3',
  },
  {
    id: 4,
    question: 'What is the standard English translation for the profound Na\'vi greeting "Oel ngati kameie"?',
    options: ['I honor you', 'I see you', 'We are one'],
    answer: 'I see you',
    evidence: 'Source: avatar1.md, question 4',
  },
  {
    id: 5,
    question: 'How does a Mountain Banshee (Ikran) signify that it has successfully "chosen" a Na\'vi hunter to be its rider?',
    options: ['It bows its head in submission.', 'It presents a gift to the hunter.', 'It attempts to kill the hunter.'],
    answer: 'It attempts to kill the hunter.',
    evidence: 'Source: avatar1.md, question 5',
  },
  {
    id: 6,
    question: 'True or False: The Tsahìk is the clan\'s spiritual leader, specifically tasked with interpreting the will of Eywa.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar1.md, question 6',
  },
  {
    id: 7,
    question: 'What specific sequence of weaponry did Colonel Quaritch use to bring down the Omaticaya Hometree?',
    options: ['Sonic emitters followed by napalm', 'Gas canisters followed by incendiaries and rockets', 'Flashbangs followed by heavy artillery'],
    answer: 'Gas canisters followed by incendiaries and rockets',
    evidence: 'Source: avatar1.md, question 7',
  },
  {
    id: 8,
    question: 'True or False: Trudy Chacon demonstrated her defection by refusing to fire her rockets during the assault on Hometree.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar1.md, question 8',
  },
  {
    id: 9,
    question: 'During the Battle for the Tree of Souls, what method did Jake Sully use to neutralize the Valkyrie shuttle?',
    options: ['He used a longbow to hit the pilot through the glass.', 'He threw a grenade into the engine intake duct.', 'He sabotaged the fuel lines prior to the engagement.'],
    answer: 'He threw a grenade into the engine intake duct.',
    evidence: 'Source: avatar1.md, question 9',
  },
  {
    id: 10,
    question: "What is the final status of Jake Sully's consciousness at the conclusion of his first journey?",
    options: ['Permanently transferred to his Avatar body', 'Returned to his human body', 'Merged with Eywa', 'Lost in the Link Room'],
    answer: 'Permanently transferred to his Avatar body',
    evidence: 'Source: avatar1.md, question 10',
  },
];

export const AVATAR_2_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: 'Which of the following children in the Sully family are the biological offspring of Jake Sully and Neytiri?',
    options: ['Kiri, Spider, and Neteyam', 'Neteyam, Lo\'ak, and Tuktirey', 'Lo\'ak, Tuktirey, and Kiri', 'Neteyam, Lo\'ak, and Spider'],
    answer: 'Neteyam, Lo\'ak, and Tuktirey',
    evidence: 'Source: avatar2.md, question 1',
  },
  {
    id: 2,
    question: 'What physical genetic marker, inherited from Jake\'s human DNA, distinguishes the Sully children from a "normal" Na\'vi of the Metkayina clan?',
    options: ['They possess bioluminescent patterns on their chests.', 'They have four fingers and a thumb on each hand, instead of only three fingers.', 'They possess thinner tails designed for forest navigation rather than swimming.', 'They lack a neural queue (ponytail) for making a bond.'],
    answer: 'They have four fingers and a thumb on each hand, instead of only three fingers.',
    evidence: 'Source: avatar2.md, question 2',
  },
  {
    id: 3,
    question: 'Who is revealed to be the biological father of the human boy Miles "Spider" Quaritch?',
    options: ['Dr. Norm Spellman', 'Parker Selfridge', 'Colonel Miles Quaritch', 'Thomas Sully'],
    answer: 'Colonel Miles Quaritch',
    evidence: 'Source: avatar2.md, question 3',
  },
  {
    id: 4,
    question: 'What is the miraculous origin of the Sully family\'s adopted daughter, Kiri?',
    options: ['She is a clone created in an RDA laboratory.', 'She was born from Grace Augustine\'s avatar after the scientist had already died.', 'She was discovered inside a Spirit Tree pod after a Great Sorrow.', 'She is the biological daughter of Neytiri\'s sister, Silwanin.'],
    answer: 'She was born from Grace Augustine\'s avatar after the scientist had already died.',
    evidence: 'Source: avatar2.md, question 4',
  },
  {
    id: 5,
    question: 'Why is the Tulkun named Payakan considered an outcast by his pod and the Metkayina clan?',
    options: ['He was unable to form a neural bond with a Na\'vi rider.', 'He was wrongly accused of being violent.', 'He failed to protect the reef spirit tree during a storm.', 'He refused to share the precious brain oil with his kin.'],
    answer: 'He was wrongly accused of being violent.',
    evidence: 'Source: avatar2.md, question 5',
  },
  {
    id: 6,
    question: 'Which physical adaptation makes it most difficult for the Sully children to keep up with the native Metkayina during their training?',
    options: ['Their inability to form a neural bond with an Ilu.', 'Their reliance on Exopacks for deep-water dives.', 'Metkayina bodies are specifically built for swimming compared to the Omatikaya.', 'The lack of bioluminescent lures on their skin.'],
    answer: 'Metkayina bodies are specifically built for swimming compared to the Omatikaya.',
    evidence: 'Source: avatar2.md, question 6',
  },
  {
    id: 7,
    question: 'To which Na\'vi clan does Jake Sully take his family to seek refuge when the RDA returns to hunt him?',
    options: ['The Tipani', 'The Tayrangi', 'The Metkayina', 'The Omatikaya'],
    answer: 'The Metkayina',
    evidence: 'Source: avatar2.md, question 7',
  },
  {
    id: 8,
    question: 'The primary motivation for the humans\' return to Pandora after 16 years is the realization that Earth is dying and humanity requires a place for colonization.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar2.md, question 8',
  },
  {
    id: 9,
    question: 'The initial surprise attack against the human whaling vessel, which causes massive damage and chaos, was launched by the Tulkun named Payakan.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar2.md, question 9',
  },
  {
    id: 10,
    question: 'At the conclusion of the battle, the primary antagonist, Colonel Quaritch, is rescued from drowning by his biological son, Spider.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Source: avatar2.md, question 10',
  },
];

export const AVATAR_3_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: "Who is the leader of the Ash People introduced in 'Avatar: Fire and Ash'?",
    options: ['Mo\'at', 'Varang', 'Neytiri', 'Tsireya'],
    answer: 'Varang',
    evidence: 'Source: avatar3.md, question 1',
  },
  {
    id: 2,
    question: 'What element do the Ash People heavily revere and use for their markings?',
    options: ['Water', 'Wind', 'Fire and Ash', 'Earth'],
    answer: 'Fire and Ash',
    evidence: 'In-universe lore: The Ash People are associated with fire and volcanic ash.',
  },
  {
    id: 3,
    question: 'Which specific spirits appear at the end of the ritual to accept Spider as one of the people?',
    options: ['Grace and Neteyam', 'Eytukan and Tsu\'tey', 'Sylwanin and Eytukan', 'Tsu\'tey and Neteyam'],
    answer: 'Eytukan and Tsu\'tey',
    evidence: 'Source: avatar3.md, question 3',
  },
  {
    id: 4,
    question: 'True or False: Kiri has a unique spiritual connection to Eywa, allowing her to control the flora and fauna of Pandora.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: Kiri shows a powerful, direct connection to Eywa and is able to influence the plants and animals of Pandora.',
  },
  {
    id: 5,
    question: 'What is the name of the Na\'vi clan that lives in the reefs and is adapted to oceanic life?',
    options: ['Metkayina', 'Omaticaya', 'Olangi', 'Tayrangi'],
    answer: 'Metkayina',
    evidence: 'In-universe lore: The Metkayina are the reef-dwelling Na\'vi clan introduced in the second part of the story.',
  },
  {
    id: 6,
    question: 'True or False: The RDA continues to colonize Pandora to extract resources because Earth is dying.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: The Resource Development Administration (RDA) returns to Pandora because Earth is becoming uninhabitable and they need a new home.',
  },
  {
    id: 7,
    question: 'What is the name of the sacred tree of the Metkayina clan, where they connect to Eywa under water?',
    options: ['The Cove of the Ancestors', 'The Tree of Souls', 'The Tree of Voices', 'The Hometree'],
    answer: 'The Cove of the Ancestors',
    evidence: 'In-universe lore: The Cove of the Ancestors (Spirit Tree) is the Metkayina\'s sacred underwater site.',
  },
  {
    id: 8,
    question: "True or False: The Ash People are known to be far more peaceful than the Omaticaya.",
    options: ['True', 'False'],
    answer: 'False',
    evidence: 'In-universe lore: They are introduced as a more hostile or antagonistic Na\'vi culture.',
  },
  {
    id: 9,
    question: "What environment do the Ash People primarily inhabit?",
    options: ['Lush rainforests', 'Coral reefs', 'Volcanic wastelands', 'Floating mountains'],
    answer: 'Volcanic wastelands',
    evidence: 'In-universe lore: The Ash People live in harsh volcanic regions.',
  },
  {
    id: 10,
    question: 'True or False: The Omaticaya rely heavily on water mounts like the Ilu for their primary transport.',
    options: ['True', 'False'],
    answer: 'False',
    evidence: 'In-universe lore: The Omaticaya rely on Ikran (banshees) and Direhorses, not the Ilu used by the Metkayina.',
  },
];

export const AVATAR_RANDOM_TRIVIA = [
  ...AVATAR_1_TRIVIA,
  ...AVATAR_2_TRIVIA,
  ...AVATAR_3_TRIVIA,
].map((question, index) => ({
  ...question,
  id: index + 1,
}));
