import type { MCTriviaQuestion } from './constants';

export const CAT_IN_THE_HAT_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: "What defining piece of clothing is the Cat famous for wearing?",
    options: ["A red and white striped hat", "A black tuxedo", "A yellow raincoat", "A blue bow tie"],
    answer: "A red and white striped hat",
    evidence: "In-universe lore: The Cat is always seen wearing his iconic red and white striped hat.",
  },
  {
    id: 2,
    question: "What are the first names of the two children who meet the Cat?",
    options: ["Suzy and Cromwell", "Sally and Conrad", "Ginny and Fred", "Denise and Allen"],
    answer: "Sally and Conrad",
    evidence: "In-universe lore: Sally and Conrad Walden are the two children who meet the Cat.",
  },
  {
    id: 3,
    question: "What is the full name of the children's mother?",
    options: ["Joan Walden", "Lucy Walden", "Mona Walden", "Esther Walden"],
    answer: "Joan Walden",
    evidence: "In-universe lore: Joan Walden is the full name of the children's mother.",
  },
  {
    id: 4,
    question: "What is the name of the babysitter tasked with watching the children?",
    options: ["Mrs. Quan", "Mrs. Qwan", "Mrs. Kwan", "Mrs. Quann"],
    answer: "Mrs. Kwan",
    evidence: "In-universe lore: Mrs. Kwan is the sleepy babysitter hired to watch the children.",
  },
  {
    id: 5,
    question: "What is the specific identity of Joan's boyfriend, who also resides in his own house nearby?",
    options: ["lawrence Quinn", "Larry Wile", "Lawrence Walden", "Larry Humberfoob"],
    answer: "lawrence Quinn",
    evidence: "In-universe lore: Lawrence Quinn is Joan Walden's lazy and scheming neighbor and boyfriend.",
  },
  {
    id: 6,
    question: "The city in which the Walden family lives is named Anville.",
    options: ["True", "False"],
    answer: "True",
    evidence: "In-universe lore: The Walden family lives in the town of Anville.",
  },
  {
    id: 7,
    question: "At the beginning of the story, Conrad is sitting on a dark green chair while Sally is on a light green chair.",
    options: ["True", "False"],
    answer: "False",
    evidence: "In-universe lore: At the beginning of the story, Conrad sits on a light green chair while Sally sits on a dark green chair.",
  },
  {
    id: 8,
    question: "Immediately following the babysitter turning on the news, what activity are Conrad and Sally engaged in before meeting the Cat?",
    options: ["Teasing the dog", "Staring out a window", "Playing a board game", "Baking cupcakes"],
    answer: "Staring out a window",
    evidence: "In-universe lore: When Mrs. Kwan turns on the news and falls asleep, Sally and Conrad stare out the window in boredom before the Cat arrives.",
  },
  {
    id: 9,
    question: "What is the full name of the Cat's vehicle, abbreviated as S.L.O.W.?",
    options: ["Super Liquid Omnipotent Watercraft", "Super Luxurious Omnidirectional Watchamajigger", "Super Low-grade Optical Wagon", "Spontaneous Luxurious Overdrive Watcher"],
    answer: "Super Luxurious Omnidirectional Watchamajigger",
    evidence: "In-universe lore: The Cat's custom multi-functional vehicle is called the Super Luxurious Omnidirectional Watchamajigger (S.L.O.W.).",
  },
  {
    id: 10,
    question: "What was the rejected predecessor name for the S.L.O.W. vehicle?",
    options: ["Super Hydraulic Instantaneous Transporter", "Mechanical Instantaneous Traveler", "Super Fast Automatic Car", "Highly Efficient Individual Transport"],
    answer: "Super Hydraulic Instantaneous Transporter",
    evidence: "In-universe lore: The Cat reveals that the predecessor name for the S.L.O.W. vehicle was the Super Hydraulic Instantaneous Transporter.",
  },
  {
    id: 11,
    question: "Which personality types are assigned to Sally and Conrad by the 'Phunometer' (or the personality machine)?",
    options: ["Liar and Truth-teller", "Control Freak and Rule Breaker", "Bed Wetter and Arsonist", "Silent and Loud"],
    answer: "Control Freak and Rule Breaker",
    evidence: "In-universe lore: The Cat's 'Phunometer' machine classifies Sally as a control freak and Conrad as a rule breaker.",
  },
  {
    id: 12,
    question: "Where was the Cat's large red wooden crate manufactured?",
    options: ["The North Pole", "Made in the Philippines", "The Seuss Landing", "Made in China"],
    answer: "Made in the Philippines",
    evidence: "In-universe lore: Conrad notices a 'Made in the Philippines' label on the Cat's crate, though the Cat claims it refers to a different universe's Philippines.",
  },
  {
    id: 13,
    question: "What specific animal shape does the lock on the Cat's crate resemble?",
    options: ["A spider", "A crab", "A lobster", "A fish"],
    answer: "A crab",
    evidence: "In-universe lore: The lock sealing the Cat's magical crate is shaped like a crab.",
  },
  {
    id: 14,
    question: "During the house's transformation into the 'Mother of All Messes,' what do Joan's cooking books turn into?",
    options: ["Flying monkeys", "Big birds", "Paper airplanes", "Singing flowers"],
    answer: "Big birds",
    evidence: "In-universe lore: During the magical transformation of the house, Joan's cooking books literally turn into flying birds with book pages for wings.",
  },
  {
    id: 15,
    question: "What is the Cat's specific response when answering the phone during the chaotic cleanup?",
    options: ["'Walden Residence'", "'City Morgue'", "'The Cat's House'", "'Wrong Number'"],
    answer: "'City Morgue'",
    evidence: "In-universe lore: When answering the phone during the chaos, the Cat playfully greets the caller with 'City Morgue'.",
  },
  {
    id: 16,
    question: "What color is the 'goop' associated with the 'Mother of All Messes'?",
    options: ["Green", "Blue", "Purple", "Pink"],
    answer: "Purple",
    evidence: "In-universe lore: The 'Mother of All Messes' produces a sticky purple goop that begins to consume the house.",
  },
  {
    id: 17,
    question: "How does the Cat initially describe the identity of his lawyers to the children?",
    options: ["'Dangerous creatures from the underworld'", "'Magical time travelling elves'", "'Students at Dieck Elementary'", "'Things from the Crate'"],
    answer: "'Magical time travelling elves'",
    evidence: "In-universe lore: The Cat jokingly claims that his legal representatives are 'magical time travelling elves'.",
  },
  {
    id: 18,
    question: "What is the defining, annoying behavioral trait of the 'Things'?",
    options: ["They only speak in rhyme", "They do the opposite of what is asked", "They hide from everyone", "They only eat Twinkies"],
    answer: "They do the opposite of what is asked",
    evidence: "In-universe lore: Thing 1 and Thing 2 are notorious for doing the exact opposite of whatever they are instructed to do.",
  },
  {
    id: 19,
    question: "What is the name of the vehicle the Cat uses to clean the house at the end of the story?",
    options: ["The D.I.R.T.", "The Sweeper 3000", "The S.L.O.P.", "The Clean-O-Matic"],
    answer: "The D.I.R.T.",
    evidence: "In-universe lore: The Cat uses the Dynamic Industrial Renovating Tractormajigger (D.I.R.T.) to sweep up and fully clean the house before Joan returns.",
  },
  {
    id: 20,
    question: "What does the Cat say to the kids before he finally leaves their house?",
    options: ["It's been fun!", "Vaya con Dios!", "Stay out of trouble!", "I'll be back!"],
    answer: "It's been fun!",
    evidence: "In-universe lore: The Cat leaves the children after successfully cleaning up.",
  },
  {
    id: 21,
    question: "True or False: The Cat in the Hat is the one who narrates the opening and closing of the story.",
    options: ["True", "False"],
    answer: "True",
    evidence: "In-universe lore: The Cat narrates the story directly to the audience.",
  },
];
