import type { MCTriviaQuestion } from './constants';

export const CAT_IN_THE_HAT_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: "Which actor portrayed the titular role of the Cat in the 2003 film?",
    options: ["Alec Baldwin", "Mike Myers", "Bo Welch", "Spencer Breslin"],
    answer: "Mike Myers",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 3: The children met the Cat in the broom closet. The Cat helped the children to be perfect. Reference: Quiz: The Cat in the Hat.",
  },
  {
    id: 2,
    question: "What are the first names of the two children who meet the Cat?",
    options: ["Suzy and Cromwell", "Sally and Conrad", "Ginny and Fred", "Denise and Allen"],
    answer: "Sally and Conrad",
    evidence: "The Cat In The Hat Quiz! Movie Trivia - Quiz, Flashcards & Trivia - Question 1: The correct answer is Sally and Conrad. The question asks for the names of the children, and out of the given options, Sally and Conrad are the only names that are mentioned.",
  },
  {
    id: 3,
    question: "What is the full name of the children's mother?",
    options: ["Joan Walden", "Lucy Walden", "Mona Walden", "Esther Walden"],
    answer: "Joan Walden",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 10: Her last name is Walden. We hear Mom's name several time in the movie.",
  },
  {
    id: 4,
    question: "What is the name of the babysitter tasked with watching the children?",
    options: ["Mrs. Quan", "Mrs. Qwan", "Mrs. Kwan", "Mrs. Quann"],
    answer: "Mrs. Kwan",
    evidence: "How well do you know The Cat in the Hat movie (very hard)? - Question 7: What is the name of the babysitter... Mrs. Kwan",
  },
  {
    id: 5,
    question: "What is the specific identity of Joan's boyfriend, who also resides in his own house nearby?",
    options: ["lawrence Quinn", "Larry Wile", "Lawrence Walden", "Larry Humberfoob"],
    answer: "lawrence Quinn",
    evidence: "How well do you know The Cat in the Hat movie (very hard)? - Question 19: What is Larry's other name... lawrence... What is larry's last name... Quinn",
  },
  {
    id: 6,
    question: "The city in which the Walden family lives is named Anville.",
    options: ["True", "False"],
    answer: "True",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 11: The name of the city in which the movie takes place? Answer: Anville. This is said at the very beginning of the movie, in the narrated introduction.",
  },
  {
    id: 7,
    question: "At the beginning of the movie, Conrad is sitting on a dark green chair while Sally is on a light green chair.",
    options: ["True", "False"],
    answer: "False",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 5: Conrad was sitting on a light green chair. Sally was sitting on a dark green chair. It was raining outside and they were bored.",
  },
  {
    id: 8,
    question: "Immediately following the babysitter turning on the news, what activity are Conrad and Sally engaged in before meeting the Cat?",
    options: ["Teasing the dog", "Staring out a window", "Playing a board game", "Baking cupcakes"],
    answer: "Staring out a window",
    evidence: "How well do you know The Cat in the Hat movie (very hard)? - Question 6: what are conrad and sally first doing before they meet the cat but after the babysitter puts on the news channel?... staring out a window",
  },
  {
    id: 9,
    question: "What is the full name of the Cat's vehicle, abbreviated as S.L.O.W.?",
    options: ["Super Liquid Omnipotent Watercraft", "Super Luxurious Omnidirectional Watchamajigger", "Super Low-grade Optical Wagon", "Spontaneous Luxurious Overdrive Watcher"],
    answer: "Super Luxurious Omnidirectional Watchamajigger",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 1: The Super Luxurious Omnidirectional Watchamajigger, or S.L.O.W. is the Cat's vehicle. He says that this name was better than the first one, which was Super Hydraulic Instantaneous Transporter.",
  },
  {
    id: 10,
    question: "What was the rejected predecessor name for the S.L.O.W. vehicle?",
    options: ["Super Hydraulic Instantaneous Transporter", "Mechanical Instantaneous Traveler", "Super Fast Automatic Car", "Highly Efficient Individual Transport"],
    answer: "Super Hydraulic Instantaneous Transporter",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 1: The Super Luxurious Omnidirectional Watchamajigger, or S.L.O.W. is the Cat's vehicle. He says that this name was better than the first one, which was Super Hydraulic Instantaneous Transporter.",
  },
  {
    id: 11,
    question: "Which personality types are assigned to Sally and Conrad by the 'Phunometer' (or the personality machine)?",
    options: ["Liar and Truth-teller", "Control Freak and Rule Breaker", "Bed Wetter and Arsonist", "Silent and Loud"],
    answer: "Control Freak and Rule Breaker",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 12: The Cat brought the phunometer with him, to test what the children were. Sally was a control freak and Conrad was a rule breaker.",
  },
  {
    id: 12,
    question: "Where was the Cat's large red wooden crate manufactured?",
    options: ["The North Pole", "Made in the Philippines", "The Seuss Landing", "Made in China"],
    answer: "Made in the Philippines",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 4: Conrad doesn't believe the Cat's big red wooden crate comes from another world because it says \"Made in the Philippines\", but the Cat insists that it is \"not in these Philippines\".",
  },
  {
    id: 13,
    question: "What specific animal shape does the lock on the Cat's crate resemble?",
    options: ["A spider", "A crab", "A lobster", "A fish"],
    answer: "A crab",
    evidence: "How well do you know The Cat in the Hat movie (very hard)? - Question 10: The crate is kept close by a lock what does it look like?... a crab",
  },
  {
    id: 14,
    question: "During the house's transformation into the 'Mother of All Messes,' what do Joan's cooking books turn into?",
    options: ["Flying monkeys", "Big birds", "Paper airplanes", "Singing flowers"],
    answer: "Big birds",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 6: at that point of the movie, the whole house is transformed into complete nonsense and we can clearly see big birds, with books for wings, passing by. One of the kids remarks that these are Mom's cooking books.",
  },
  {
    id: 15,
    question: "What is the Cat's specific response when answering the phone during the chaotic cleanup?",
    options: ["'Walden Residence'", "'City Morgue'", "'The Cat's House'", "'Wrong Number'"],
    answer: "'City Morgue'",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 8: the phone rings and the Cat answers \"City Morgue\"! According to the fish, this is the 18th house rule that the Cat breaks.",
  },
  {
    id: 16,
    question: "What color is the 'goop' associated with the 'Mother of All Messes'?",
    options: ["Green", "Blue", "Purple", "Pink"],
    answer: "Purple",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 14: The Mother of all messes had purple goop coming out of it. Yuck!",
  },
  {
    id: 17,
    question: "How does the Cat initially describe the identity of his lawyers to the children?",
    options: ["'Dangerous creatures from the underworld'", "'Magical time travelling elves'", "'Students at Dieck Elementary'", "'Things from the Crate'"],
    answer: "'Magical time travelling elves'",
    evidence: "The Cat In The Hat Quiz! Movie Trivia - Quiz, Flashcards & Trivia - Question 7: The cat in the hat says his lawyers are magical time travelling elves at first. This implies that the cat in the hat is making a playful and imaginative statement about his lawyers...",
  },
  {
    id: 18,
    question: "What is the defining, annoying behavioral trait of the 'Things'?",
    options: ["They only speak in rhyme", "They do the opposite of what is asked", "They hide from everyone", "They only eat Twinkies"],
    answer: "They do the opposite of what is asked",
    evidence: "The Cat In The Hat Quiz! Movie Trivia - Quiz, Flashcards & Trivia - Question 2: The given correct answer suggests that what is annoying about \"things\" is that when you ask them to do something, they do the opposite.",
  },
  {
    id: 19,
    question: "Who served as the director of the 2003 live-action 'The Cat in the Hat'?",
    options: ["Dr. Seuss", "Bo Welch", "Mike Myers", "Alec Baldwin"],
    answer: "Bo Welch",
    evidence: "14 The Cat in the Hat Trivia Questions & Answers | Movies A-C - Question 9: Who directed this film? Answer: Bo Welch. Bo Welch kept making mistakes and telling the cat to act out the wrong things. This was in the outakes on the special features.",
  },
  {
    id: 20,
    question: "What significant reaction did Dr. Seuss's widow have to the film's release?",
    options: ["She commissioned a sequel", "She decided there would be no more on-screen live-action adaptations", "She requested Mike Myers play all future characters", "She sold the rights to a different studio"],
    answer: "She decided there would be no more on-screen live-action adaptations",
    evidence: "The Cat In The Hat Quiz! Movie Trivia - Quiz, Flashcards & Trivia - About This Quiz: Dr. Seuss's widow decided after that there would be no more on-screen adaptions of her husband's work.",
  },
  {
    id: 21,
    question: "The Cat serves as the film's narrator.",
    options: ["True", "False"],
    answer: "True",
    evidence: "How well do you know The Cat in the Hat movie (very hard)? - Question 37: Who was actually the narrator... the cat",
  },
];
