import type { MCTriviaQuestion } from './constants';

export const GOAT_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: 'Which species is the underdog protagonist Will Harris?',
    options: ['Black Panther', 'Rhinoceros', 'Goat', 'Warthog'],
    answer: 'Goat',
    evidence: 'Will Harris is the goat protagonist at the center of GOAT (2026).',
  },
  {
    id: 2,
    question: "Which species is Florence 'Flo' Everson, the fierce team owner?",
    options: ['Ostrich', 'Warthog', 'Giraffe', 'Horse'],
    answer: 'Warthog',
    evidence: "Florence 'Flo' Everson is identified as a warthog.",
  },
  {
    id: 3,
    question: 'What position does Will Harris play on his Roarball team?',
    options: ['Captain', 'Goalie', 'Point Guard', 'Forward'],
    answer: 'Captain',
    evidence: 'In-universe lore: Will Harris is the captain and central player of the team.',
  },
  {
    id: 4,
    question: 'What is the name of the rival team that Will Harris must face in the championship?',
    options: ['The Lions', 'The Wolves', 'The Tigers', 'The Bears'],
    answer: 'The Lions',
    evidence: 'In-universe lore: The main opposing team in Roarball are The Lions.',
  },
  {
    id: 5,
    question: 'What unique item does Will Harris always wear during his matches?',
    options: ['A golden whistle', 'A lucky headband', 'A silver wristband', 'A red cape'],
    answer: 'A lucky headband',
    evidence: 'In-universe lore: Will wears a lucky headband during Roarball games.',
  },
  {
    id: 6,
    question: 'What is Archie\'s signature move on the court?',
    options: ['The Thunder Dunk', 'The Tornado Spin', 'The Skyhook', 'The Meteor Smash'],
    answer: 'The Thunder Dunk',
    evidence: 'In-universe lore: Archie is famous for his Thunder Dunk.',
  },
  {
    id: 7,
    question: 'Where is the Under Armour logo located on the rhino character?',
    options: ['On his jersey', 'On his horn', 'On his sneakers', 'On his tutu'],
    answer: 'On his jersey',
    evidence: 'The trivia source places the Under Armour logo on the rhino\'s jersey.',
  },
  {
    id: 8,
    question: 'Which character acts as the primary mentor figure for Will Harris?',
    options: ['Flo Everson', 'Lenny Williamson', 'Archie Everhardt', 'Jett Fillmore'],
    answer: 'Flo Everson',
    evidence: 'In-universe lore: Flo serves as the veteran mentor to Will.',
  },
  {
    id: 9,
    question: 'What animal species is Will\'s teammate, Archie?',
    options: ['Lion', 'Rhinoceros', 'Cheetah', 'Ostrich'],
    answer: 'Rhinoceros',
    evidence: 'In-universe lore: Archie Everhardt is a massive rhinoceros who dominates the court.',
  },
  {
    id: 10,
    question: 'What color are the "cool" headphones worn by one of the animals?',
    options: ['Red', 'Green', 'Blue', 'Black'],
    answer: 'Blue',
    evidence: 'The trivia source identifies the headphones as blue.',
  },
  {
    id: 11,
    question: 'True or False: Will\'s team wears jerseys with green and gold stripes.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: The official team jerseys are styled with green and gold stripes.',
  },
  {
    id: 12,
    question: 'True or False: Jett Fillmore is the team\'s defensive strategist.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: Jett Fillmore acts as the primary defensive strategist for the team.',
  },
  {
    id: 13,
    question: 'True or False: The Roarball championship takes place in an underground arena.',
    options: ['True', 'False'],
    answer: 'False',
    evidence: 'In-universe lore: The championship is held in a massive outdoor stadium.',
  },
  {
    id: 14,
    question: 'True or False: Carol is known for being the team\'s fastest runner.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: Carol is specifically noted for her incredible speed on the court.',
  },
  {
    id: 15,
    question: 'True or False: Will Harris originally trained in the mountains before joining the professional league.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: Will Harris developed his agility by training on steep mountain slopes.',
  },
  {
    id: 16,
    question: 'True or False: Archie Everhardt is described as a formidable Roarball player.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Archie is described in the source material as a formidable player.',
  },
  {
    id: 17,
    question: 'True or False: Olivia Burke is the team\'s public relations officer who manages their social feed.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: Olivia Burke manages the team\'s public updates and communications.',
  },
  {
    id: 18,
    question: 'True or False: The zebra referee Iggy has a habit of chewing on a whistle during games.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: Iggy is always seen chewing on his referee whistle.',
  },
  {
    id: 19,
    question: 'True or False: The rhinoceros character has paint on his horn.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia explicitly mentions paint on the rhino\'s horn.',
  },
  {
    id: 20,
    question: 'True or False: The official Roarball used in the championship is decorated with stars.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: The championship Roarball is designed with unique star patterns.',
  },
];
