import type { MCTriviaQuestion } from './constants';

export const GOAT_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: 'Which species is the underdog protagonist Will Harris?',
    options: ['Black Panther', 'Rhinoceros', 'Goat', 'Warthog'],
    answer: 'Goat',
    evidence: 'Will Harris is the goat protagonist at the center of GOAT (2026).',
  },
  {
    id: 2,
    question: "Which species is Florence 'Flo' Everson, the fierce team owner?",
    options: ['Ostrich', 'Warthog', 'Giraffe', 'Horse'],
    answer: 'Warthog',
    evidence: "Florence 'Flo' Everson is identified as a warthog.",
  },
  {
    id: 3,
    question: 'What is the film\'s Polish title?',
    options: ['Sogna in Grande', 'Wielka mała koza', 'Um Cabra Bom de Bola', 'Tuyển thủ Dê'],
    answer: 'Wielka mała koza',
    evidence: 'The Polish release title is Wielka mała koza.',
  },
  {
    id: 4,
    question: 'Which real-world athlete voices Lenny Williamson and is also a producer on the film?',
    options: ['Andre Iguodala', 'Dwyane Wade', 'Caleb McLaughlin', 'Stephen Curry'],
    answer: 'Stephen Curry',
    evidence: 'Stephen Curry voices Lenny Williamson and also holds a producer credit.',
  },
  {
    id: 5,
    question: 'The February 13, 2026 release date was timed to coincide with which event?',
    options: ['The Super Bowl', 'NBA All-Star Weekend', 'Chinese New Year', 'The Zootopia 2 premiere'],
    answer: 'NBA All-Star Weekend',
    evidence: 'The release aligns with the first day of NBA All-Star Weekend 2026.',
  },
  {
    id: 6,
    question: 'Who voiced Archie in the Malaysian release of the film?',
    options: ['Zulkifli Ariffin', 'David Harbour', 'Eduardo Franco', 'Mamoru Hosoda'],
    answer: 'Zulkifli Ariffin',
    evidence: 'The Malaysian dub credits Zulkifli Ariffin as Archie.',
  },
  {
    id: 7,
    question: 'Where is the Under Armour logo located on the rhino character?',
    options: ['On his jersey', 'On his horn', 'On his sneakers', 'On his tutu'],
    answer: 'On his jersey',
    evidence: 'The trivia source places the Under Armour logo on the rhino\'s jersey.',
  },
  {
    id: 8,
    question: 'GOAT released its trailer on July 30, 2025, the same day as the trailer for which film?',
    options: ['Scarlet', 'Zootopia 2', 'Beastars', 'Stranger Things'],
    answer: 'Zootopia 2',
    evidence: 'The GOAT trailer date matches the Zootopia 2 trailer date.',
  },
  {
    id: 9,
    question: 'The Vietnamese title contains a pun referencing what?',
    options: ['Goat cheese', 'The Chinese Zodiac Year of the Goat', 'The scent of victory', 'A local Roarball team'],
    answer: 'The Chinese Zodiac Year of the Goat',
    evidence: 'The title pun ties to the Year of the Goat.',
  },
  {
    id: 10,
    question: 'What color are the "cool" headphones worn by one of the animals?',
    options: ['Red', 'Green', 'Blue', 'Black'],
    answer: 'Blue',
    evidence: 'The trivia source identifies the headphones as blue.',
  },
  {
    id: 11,
    question: 'True or False: Will Harris was added as an exclusive character called "GOAT" to the game Steal a Brainrot in January 2026.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia notes that Will Harris appeared in Steal a Brainrot in January 2026.',
  },
  {
    id: 12,
    question: 'True or False: Early production notes say Jett Fillmore was originally intended to be male.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia notes that Jett was at one point male.',
  },
  {
    id: 13,
    question: 'True or False: The film\'s novelization was released on January 6, 2026 before the theatrical release.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The novelization release date in the supplied trivia is January 6, 2026.',
  },
  {
    id: 14,
    question: 'True or False: Ayesha Curry voices the character Carol.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia credits Ayesha Curry as the voice of Carol.',
  },
  {
    id: 15,
    question: 'True or False: The Brazilian title "Um Cabra Bom de Bola" uses a pun where "cabra" can mean both a goat and a tough man.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia explains the double meaning of cabra in the Brazilian title.',
  },
  {
    id: 16,
    question: 'True or False: Archie Everhardt is described as a formidable Roarball player.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Archie is described in the source material as a formidable player.',
  },
  {
    id: 17,
    question: 'True or False: Deleted scenes show Olivia Burke sticking her head into a bucket of sand to find her phone.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'That deleted-scene detail appears in the supplied trivia.',
  },
  {
    id: 18,
    question: 'True or False: The zebra referee Iggy is voiced by former NBA player Andre Iguodala.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia ties Iggy directly to Andre Iguodala.',
  },
  {
    id: 19,
    question: 'True or False: The rhinoceros character has paint on his horn.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia explicitly mentions paint on the rhino\'s horn.',
  },
  {
    id: 20,
    question: 'True or False: The basketball in the movie is decorated with stars.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia says the basketball has stars on it.',
  },
];
