import type { MCTriviaQuestion } from './constants';

export const GOAT_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: 'Which species is the underdog protagonist Will Harris?',
    options: ['Black Panther', 'Rhinoceros', 'Goat', 'Warthog'],
    answer: 'Goat',
    evidence: 'Will Harris is the goat protagonist at the center of GOAT (2026).',
  },
  {
    id: 2,
    question: "Which species is Florence 'Flo' Everson, the fierce team owner?",
    options: ['Ostrich', 'Warthog', 'Giraffe', 'Horse'],
    answer: 'Warthog',
    evidence: "Florence 'Flo' Everson is identified as a warthog.",
  },
  {
    id: 3,
    question: 'What is the film\'s Polish title?',
    options: ['Sogna in Grande', 'Wielka mała koza', 'Um Cabra Bom de Bola', 'Tuyển thủ Dê'],
    answer: 'Wielka mała koza',
    evidence: 'The Polish release title is Wielka mała koza.',
  },
  {
    id: 4,
    question: 'What is the name of the rival team that Will Harris must face in the championship?',
    options: ['The Lions', 'The Wolves', 'The Tigers', 'The Bears'],
    answer: 'The Lions',
    evidence: 'In-universe lore: The main opposing team in Roarball are The Lions.',
    id: 5,
    question: 'What unique item does Will Harris always wear during his matches?',
    options: ['A golden whistle', 'A lucky headband', 'A silver wristband', 'A red cape'],
    answer: 'A lucky headband',
    evidence: 'In-universe lore: Will wears a lucky headband during Roarball games.',
  },
  {
    id: 6,
    question: 'What is Archie\'s signature move on the court?',
    options: ['The Thunder Dunk', 'The Tornado Spin', 'The Skyhook', 'The Meteor Smash'],
    answer: 'The Thunder Dunk',
    evidence: 'In-universe lore: Archie is famous for his Thunder Dunk.',
  },
  {
    id: 7,
    question: 'Where is the Under Armour logo located on the rhino character?',
    options: ['On his jersey', 'On his horn', 'On his sneakers', 'On his tutu'],
    answer: 'On his jersey',
    evidence: 'The trivia source places the Under Armour logo on the rhino\'s jersey.',
  },
  {
    id: 8,
    question: 'Which character acts as the primary mentor figure for Will Harris?',
    options: ['Flo Everson', 'Lenny Williamson', 'Archie Everhardt', 'Jett Fillmore'],
    answer: 'Flo Everson',
    evidence: 'In-universe lore: Flo serves as the veteran mentor to Will.',
  },
  {
    id: 9,
    question: 'The Vietnamese title contains a pun referencing what?',
    options: ['Goat cheese', 'The Chinese Zodiac Year of the Goat', 'The scent of victory', 'A local Roarball team'],
    answer: 'The Chinese Zodiac Year of the Goat',
    evidence: 'The title pun ties to the Year of the Goat.',
  },
  {
    id: 10,
    question: 'What color are the "cool" headphones worn by one of the animals?',
    options: ['Red', 'Green', 'Blue', 'Black'],
    answer: 'Blue',
    evidence: 'The trivia source identifies the headphones as blue.',
  },
  {
    id: 11,
    question: 'True or False: Will Harris was added as an exclusive character called "GOAT" to the game Steal a Brainrot in January 2026.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia notes that Will Harris appeared in Steal a Brainrot in January 2026.',
  },
  {
    id: 12,
    question: 'True or False: Early production notes say Jett Fillmore was originally intended to be male.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia notes that Jett was at one point male.',
  },
  {
    id: 13,
    question: 'True or False: The Roarball championship takes place in an underground arena.',
    options: ['True', 'False'],
    answer: 'False',
    evidence: 'In-universe lore: The championship is held in a massive outdoor stadium.',
  },
  {
    id: 14,
    question: 'True or False: Carol is known for being the team\'s fastest runner.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: Carol is specifically noted for her incredible speed on the court.',
  },
  {
    id: 15,
    question: 'True or False: The Brazilian title "Um Cabra Bom de Bola" uses a pun where "cabra" can mean both a goat and a tough man.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia explains the double meaning of cabra in the Brazilian title.',
  },
  {
    id: 16,
    question: 'True or False: Archie Everhardt is described as a formidable Roarball player.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'Archie is described in the source material as a formidable player.',
  },
  {
    id: 17,
    question: 'True or False: Deleted scenes show Olivia Burke sticking her head into a bucket of sand to find her phone.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'That deleted-scene detail appears in the supplied trivia.',
  },
  {
    id: 18,
    question: 'True or False: The zebra referee Iggy has a habit of chewing on a whistle during games.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'In-universe lore: Iggy is always seen chewing on his referee whistle.',
  },
  {
    id: 19,
    question: 'True or False: The rhinoceros character has paint on his horn.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia explicitly mentions paint on the rhino\'s horn.',
  },
  {
    id: 20,
    question: 'True or False: The basketball in the movie is decorated with stars.',
    options: ['True', 'False'],
    answer: 'True',
    evidence: 'The supplied trivia says the basketball has stars on it.',
  },
];
