import type { MCTriviaQuestion } from './constants';

export const MINECRAFT_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: "What did Steve describe as his childhood yearning?",
    options: ["Building a castle", "Farming wheat", "Digging the mines", "Taming a dragon"],
    answer: "Digging the mines",
    evidence: "In-universe lore: Steve recounts that since his childhood, he has yearned for the mines.",
  },
  {
    id: 2,
    question: "True or False: The character Henry is actually young Steve.",
    options: ["True", "False"],
    answer: "False",
    evidence: "In-universe lore: Henry and young Steve are two distinct characters.",
  },
  {
    id: 3,
    question: "What color shirt does Steve traditionally wear in the Minecraft universe?",
    options: ["Red", "Green", "Light Blue", "Yellow"],
    answer: "Light Blue",
    evidence: "In-universe lore: Steve's classic default appearance features a light blue shirt.",
  },
  {
    id: 4,
    question: "What is the professional nickname that Garrett Garrison calls himself?",
    options: ["The Trash Man", "The Bin Man", "The Garbage Man", "The Dusty Man"],
    answer: "The Garbage Man",
    evidence: "In-universe lore: Garrett Garrison refers to himself as 'The Garbage Man'.",
  },
  {
    id: 5,
    question: "In what year did Garrett win the 'Gamer of the Year' award?",
    options: ["1989", "1990", "1999", "2010"],
    answer: "1990",
    evidence: "In-universe lore: Garrett won the 'Gamer of the Year' award in 1990.",
  },
  {
    id: 6,
    question: "What was the first item that Garrett successfully crafted?",
    options: ["A wooden sword", "A stone pickaxe", "A bucket", "A crafting table"],
    answer: "A bucket",
    evidence: "In-universe lore: The first item Garrett managed to craft in the new world was a bucket.",
  },
  {
    id: 7,
    question: "True or False: In the story, the phrase 'Vaya con Dios' translates to 'Thank you'.",
    options: ["True", "False"],
    answer: "False",
    evidence: "In-universe lore: The Spanish phrase 'Vaya con Dios' translates to 'Go with God'.",
  },
  {
    id: 8,
    question: "What specific items must be combined to open a portal to the Overworld?",
    options: ["Flint and Steel", "Orb and Crystal", "Eye of Ender and Frame", "Redstone and Obsidian"],
    answer: "Orb and Crystal",
    evidence: "In-universe lore: Combining the magical orb and crystal opens a passage back to the Overworld.",
  },
  {
    id: 9,
    question: "What is the primary objective of Steve and his friends?",
    options: ["To build a city", "To save the Overworld", "To find Herobrine", "To mine all the diamond"],
    answer: "To save the Overworld",
    evidence: "In-universe lore: Steve and his companions embark on a quest to save the Overworld from destruction.",
  },
  {
    id: 10,
    question: "True or False: Villagers are total pacifists and vegetarians.",
    options: ["True", "False"],
    answer: "True",
    evidence: "In-universe lore: Villagers are peaceful pacifists who do not fight back and consume vegetarian foods like bread.",
  },
  {
    id: 11,
    question: "What role does the Iron Golem play in the village?",
    options: ["Blacksmith", "Local security force", "Farmer", "Mining assistant"],
    answer: "Local security force",
    evidence: "In-universe lore: The Iron Golem acts as a protective security force for the villagers.",
  },
  {
    id: 12,
    question: "True or False: The ruler of the Nether is a character named Malgosha.",
    options: ["True", "False"],
    answer: "True",
    evidence: "In-universe lore: Malgosha is the ruler of the Nether realm.",
  },
  {
    id: 13,
    question: "What is the favorite food of the villagers, which they enjoy 'crushing'?",
    options: ["Buttloads of bread", "Crushing a loaf of meat", "Baked potatoes", "Golden apples"],
    answer: "Buttloads of bread",
    evidence: "In-universe lore: Villagers love eating bread and are described as 'crushing a loaf'.",
  },
  {
    id: 14,
    question: "True or False: Sheep in the world are typically pink.",
    options: ["True", "False"],
    answer: "True",
    evidence: "In-universe lore: The wild sheep in this particular world are pink.",
  },
  {
    id: 15,
    question: "What is the name of the dimension where Endermen originate?",
    options: ["The Nether", "The Aether", "The Overworld", "The End"],
    answer: "The End",
    evidence: "In-universe lore: Endermen are native to The End dimension.",
  },
  {
    id: 16,
    question: "True or False: You can safely sleep in a bed while in the Nether.",
    options: ["True", "False"],
    answer: "False",
    evidence: "In-universe lore: Attempting to sleep in a bed in the Nether causes it to explode.",
  },
  {
    id: 17,
    question: "True or False: Diamond is the most durable material for tools in the Minecraft universe.",
    options: ["True", "False"],
    answer: "False",
    evidence: "In-universe lore: Netherite is more durable than diamond.",
  },
  {
    id: 18,
    question: "What animal was Dawn keeping in her car?",
    options: ["Llamas/alpacas", "Goats", "Pigs", "Frogs"],
    answer: "Llamas/alpacas",
    evidence: "In-universe lore: Dawn was keeping llamas or alpacas in her vehicle.",
  },
  {
    id: 19,
    question: "True or False: Malgosha, the ruler of the Nether, always dreamed of being a world-class dancer.",
    options: ["True", "False"],
    answer: "True",
    evidence: "In-universe lore: Malgosha dreamed of becoming a professional dancer when she was young.",
  },
  {
    id: 20,
    question: "What is the name of Steve's pet dog/wolf?",
    options: ["Kevin", "Lennie", "Danny", "Dennis"],
    answer: "Dennis",
    evidence: "In-universe lore: Steve's pet dog is named Dennis.",
  },
  {
    id: 21,
    question: "True or False: The character Marlene runs over Steve with a car.",
    options: ["True", "False"],
    answer: "False",
    evidence: "In-universe lore: Marlene accidentally hits a villager with her car, not Steve.",
  },
  {
    id: 22,
    question: "Which enemy faction serves as the primary threat?",
    options: ["Endermen", "Zombies", "Piglins", "Skeletons"],
    answer: "Piglins",
    evidence: "In-universe lore: The Piglins are the main hostile faction invading the Overworld from the Nether.",
  },
  {
    id: 23,
    question: "What item did Steve use to tame his dog, Dennis?",
    options: ["Steak", "Rotten Flesh", "Femur bone", "Chicken"],
    answer: "Femur bone",
    evidence: "In-universe lore: Steve tamed Dennis by giving him a femur bone.",
  },
  {
    id: 24,
    question: "True or False: The character Natalie and Henry are siblings.",
    options: ["True", "False"],
    answer: "True",
    evidence: "In-universe lore: Henry is Natalie's brother.",
  },
  {
    id: 25,
    question: "Which iconic Minecraft mob is noted for having black eyes?",
    options: ["Zombie", "Skeleton", "Enderman", "Creeper"],
    answer: "Creeper",
    evidence: "In-universe lore: The Creeper is noted for having solid black eyes in this world.",
  },
];
