import type { MCTriviaQuestion } from './constants';

export const MINECRAFT_TRIVIA: MCTriviaQuestion[] = [
  {
    id: 1,
    question: "What did Steve describe as his childhood yearning in the movie?",
    options: ["Building a castle", "Farming wheat", "Digging the mines", "Taming a dragon"],
    answer: "Digging the mines",
    evidence: "Daily Quiz Transcript - Cast & Characters: Steve has always wanted to dig the mine. As a child I yearned for the mines.",
  },
  {
    id: 2,
    question: "True or False: The character Henry is actually young Steve.",
    options: ["True", "False"],
    answer: "False",
    evidence: "Quiz Blitz Transcript - Cast & Characters: That's young Steve. True or false? False! That's Henry.",
  },
  {
    id: 3,
    question: "Which actor portrays the character Steve?",
    options: ["Jason Momoa", "Jack Black", "Ryan Gosling", "Paul Mescal"],
    answer: "Jack Black",
    evidence: "Mused Trivia Blog - Cast & Characters: Which actor plays the character Steve in the film? D: Jack Black.",
  },
  {
    id: 4,
    question: "What is the professional nickname used by Jason Momoa's character, Garrett Garrison?",
    options: ["The Trash Man", "The Bin Man", "The Garbage Man", "The Dusty Man"],
    answer: "The Garbage Man",
    evidence: "Mused Trivia Blog - Cast & Characters: What does Jason Momoa's character, Garrett Garrison, call himself? C: The Garbage Man.",
  },
  {
    id: 5,
    question: "In what year did Garrett win the 'Gamer of the Year' award?",
    options: ["1989", "1990", "1999", "2010"],
    answer: "1990",
    evidence: "TriviaCreator - Plot Points: what year did Garret win the gamer of the year award... It was 1990.",
  },
  {
    id: 6,
    question: "What was the first item that Garrett successfully crafted?",
    options: ["A wooden sword", "A stone pickaxe", "A bucket", "A crafting table"],
    answer: "A bucket",
    evidence: "Daily Quiz Transcript - Lore & Items: What was the first thing the garbage man crafted... bucket.",
  },
  {
    id: 7,
    question: "True or False: According to the movie, the phrase 'Vaya con Dios' translates to 'Thank you'.",
    options: ["True", "False"],
    answer: "False",
    evidence: "Quiz Blitz Transcript - Lore & Items: \"Vaya con dios\" means \"Thank you\". True or false? False! It means \"Goodbye\" in Spanish.",
  },
  {
    id: 8,
    question: "What specific items must be combined to open a portal to the Overworld?",
    options: ["Flint and Steel", "Orb and Crystal", "Eye of Ender and Frame", "Redstone and Obsidian"],
    answer: "Orb and Crystal",
    evidence: "Daily Quiz Transcript - Plot Points: what happens when you combine orb and a crystal it brings you to the overworld.",
  },
  {
    id: 9,
    question: "What is the primary objective of Steve and his friends in the film?",
    options: ["To build a city", "To save the Overworld", "To find Herobrine", "To mine all the diamond"],
    answer: "To save the Overworld",
    evidence: "CrowdParty Blog - Plot Points: What is the reported plot of the Minecraft movie? A quest to save the Overworld.",
  },
  {
    id: 10,
    question: "True or False: Villagers in the movie are portrayed as total pacifists and vegetarians.",
    options: ["True", "False"],
    answer: "True",
    evidence: "Daily Quiz Transcript - Cast & Characters: they're total pacifists and vegetarians... villagers love eating bread.",
  },
  {
    id: 11,
    question: "What role does the Iron Golem play in the movie's village?",
    options: ["Blacksmith", "Local security force", "Farmer", "Mining assistant"],
    answer: "Local security force",
    evidence: "Daily Quiz Transcript - Plot Points: what role does the Iron Gollum play in the movie... local security force.",
  },
  {
    id: 12,
    question: "True or False: The ruler of the Nether is a character named Malgosha.",
    options: ["True", "False"],
    answer: "True",
    evidence: "Daily Quiz Transcript - Cast & Characters: who's the ruler of the Nether... malgosia.",
  },
  {
    id: 13,
    question: "What is the favorite food of the villagers, which they enjoy 'crushing' in the film?",
    options: ["Buttloads of bread", "Crushing a loaf of meat", "Baked potatoes", "Golden apples"],
    answer: "Buttloads of bread",
    evidence: "Daily Quiz Transcript - Lore & Items: villagers love eating bread... eat buttloads of bread they love crushing a loaf.",
  },
  {
    id: 14,
    question: "True or False: Sheep in the world of the Minecraft movie are typically pink.",
    options: ["True", "False"],
    answer: "True",
    evidence: "Quiz Blitz Transcript - Lore & Items: In Minecraft, sheep are blue. True or false? Wrong! They're pink.",
  },
  {
    id: 15,
    question: "Who is the director of 'A Minecraft Movie'?",
    options: ["Steven Spielberg", "Jared Hess", "Wes Anderson", "JJ Abrams"],
    answer: "Jared Hess",
    evidence: "Mused Trivia Blog - Production Details: Who directed A Minecraft Movie? A: Jared Hess.",
  },
  {
    id: 16,
    question: "True or False: The filming of the movie took place in New Zealand.",
    options: ["True", "False"],
    answer: "True",
    evidence: "Mused Trivia Blog - Production Details: Where was the movie filmed? D: New Zealand.",
  },
  {
    id: 17,
    question: "True or False: The movie is officially scheduled for release in the year 2025.",
    options: ["True", "False"],
    answer: "True",
    evidence: "CrowdParty Blog - Production Details: What is the planned release year for the Minecraft movie? 2025.",
  },
  {
    id: 18,
    question: "What animal was Dawn keeping in her car during the movie?",
    options: ["Llamas/alpacas", "Goats", "Pigs", "Frogs"],
    answer: "Llamas/alpacas",
    evidence: "TriviaCreator - Lore & Items: What animal did dawn have in her car... D Llamas/alpacas.",
  },
  {
    id: 19,
    question: "True or False: Malgosha, the ruler of the Nether, always dreamed of being a world-class dancer.",
    options: ["True", "False"],
    answer: "True",
    evidence: "Daily Quiz Transcript - Cast & Characters: What's the dream of Mal Gosha when she was a child... mal gosha always dreamed of being a worldclass dancer.",
  },
  {
    id: 20,
    question: "What is the name of Steve's pet dog/wolf in the movie?",
    options: ["Kevin", "Lennie", "Danny", "Dennis"],
    answer: "Dennis",
    evidence: "TriviaCreator - Cast & Characters: Steve's pet dog is called... C Dennis.",
  },
  {
    id: 21,
    question: "True or False: The character Marlene runs over Steve with a car.",
    options: ["True", "False"],
    answer: "False",
    evidence: "Quiz Blitz Transcript - Plot Points: Marlene runs over Steve with a car. True or false? ...Wrong! She runs over a villager.",
  },
  {
    id: 22,
    question: "Which enemy faction serves as the primary threat in the Minecraft movie?",
    options: ["Endermen", "Zombies", "Piglins", "Skeletons"],
    answer: "Piglins",
    evidence: "Daily Quiz Transcript - Lore & Items: what's the main enemy faction in the Minecraft movie... definitely is B piglins.",
  },
  {
    id: 23,
    question: "What item did Steve use to tame his dog, Dennis?",
    options: ["Steak", "Rotten Flesh", "Femur bone", "Chicken"],
    answer: "Femur bone",
    evidence: "Daily Quiz Transcript - Lore & Items: what did Steve use to tame Dennis... it's a femur bone.",
  },
  {
    id: 24,
    question: "True or False: The character Natalie and Henry are siblings.",
    options: ["True", "False"],
    answer: "True",
    evidence: "Quiz Blitz Transcript - Cast & Characters: Henry is Natalie's brother. True or false? It's TRUE.",
  },
  {
    id: 25,
    question: "Which iconic Minecraft mob is reported to play a major role in the movie and is noted for having black eyes?",
    options: ["Zombie", "Skeleton", "Enderman", "Creeper"],
    answer: "Creeper",
    evidence: "CrowdParty Blog - Lore & Items: Which iconic Minecraft mob will reportedly play a major role in the movie? Creeper. What color are Creeper's eyes? Black.",
  },
];
